before_script:
  - "sh -e /etc/init.d/xvfb start"
script: "DISPLAY=:99.0 bundle exec rake"

rvm:
  - "1.8.7"
  - "1.9.2"
  - "1.9.3"
  - "ree"
  - "jruby"
  - "rbx"

env:
 - "rails2"
 - "rails2_3_5"
 - "rails3"
 - "pojs-rspec1"
 - "pojs-rspec2"
